// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Businesses_Accounting.Models;

public partial class CreateAccountingJournalViewModel
{
    public int? Id { get; set; }

    public int? DocumentId { get; set; }
    [UIHint("AccountEditor")]
    [Display(Name = "حساب")]
    public int AccountId { get; set; } = 1;
    public string? Accounttxt { get; set; }

    public int? SubAccountId { get; set; }

    public string? SubAccount { get; set; }

    public string? Description { get; set; }
    [Display(Name = "بدهکار")]
    [UIHint("Currency")]
    public decimal Debit { get; set; }
    [Display(Name = "بستانکار")]
    [UIHint("Currency")]
    public decimal Credit { get; set; }

    public int? CurrencyId { get; set; }
    [UIHint("Currency")]
    [Display(Name = "مبلغ")]
    public int Amount { get; set; }

    public virtual Account Account { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual Document Document { get; set; }

    public virtual SubAccount SubAccountNavigation { get; set; }
    

}