// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace Businesses_Accounting.Models;
public class AccountValidationAttribute : ValidationAttribute  //, IClientModelValidator
{
    public override bool IsValid(object value)
    {

        if (value == null) {  return false; }
        var accountId = (int)value;
        if (accountId < 1)
        {
            return false;
        }
        return true;
    }

    //public IEnumerable<ModelClientValidationRule> GetClientValidationRules(ClientModelValidationContext context)
    //{
    //	yield return new ModelClientValidationRule("productnamevalidation", ErrorMessage);
    //}
}
public partial class CreateAccountingJournalViewModel
{
    public int? Id { get; set; }

    public int? DocumentId { get; set; }
    [UIHint("AccountEditor")]
    [Display(Name = "حساب")]
    [Required]
    [AccountValidationAttribute]
    public int? AccountId { get; set; }
    public string Accounttxt { get; set; }

    public int? SubAccountId { get; set; }

    public string? SubAccount { get; set; }

    public string? Description { get; set; }
    [Display(Name = "بدهکار")]
    [UIHint("Currency")]
    public decimal Debit { get; set; }
    [Display(Name = "بستانکار")]
    [UIHint("Currency")]
    public decimal Credit { get; set; }

    public int? CurrencyId { get; set; }
    [UIHint("Currency")]
    [Display(Name = "مبلغ")]
    public int Amount { get; set; }

    public virtual Account Account { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual Document Document { get; set; }

    public virtual SubAccount SubAccountNavigation { get; set; }


}