// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Humanizer;
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models.ViewModels;

public partial class CreateBusinessBankingViewModel
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public int BankingId { get; set; } = 1;

    public bool IsActive { get; set; } = true;

    public string Name { get; set; }

    public int CurrencyId { get; set; }

    public bool IsDefault { get; set; }

    public string Note { get; set; }
}