// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BankingType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BusinessBanking> BusinessBankings { get; set; } = new List<BusinessBanking>();
}