// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessCategory
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CategoryType { get; set; }

    public int? ParentId { get; set; }

    public int BusinessId { get; set; }

    public virtual Business Business { get; set; }

    public virtual ICollection<BusinessProduct> BusinessProducts { get; set; } = new List<BusinessProduct>();

    public virtual ICollection<BusinessService> BusinessServices { get; set; } = new List<BusinessService>();

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual ICollection<SalesmenPercentCategory> SalesmenPercentCategories { get; set; } = new List<SalesmenPercentCategory>();
}