// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessUser
{
    public int Id { get; set; }

    public Guid UserId { get; set; }

    public int BusinessId { get; set; }

    public int AccessTypeId { get; set; }

    public virtual Business Business { get; set; }

    public virtual AspNetUser User { get; set; }
}