// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessProject
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public bool IsDefault { get; set; }

    public virtual Business Business { get; set; }

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();
}