// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class Business
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int LanguageId { get; set; }

    public string LegalName { get; set; }

    public int TypeId { get; set; }

    public string BusinessLine { get; set; }

    public string NationalCode { get; set; }

    public string EconomicCode { get; set; }

    public string RegistrationNumber { get; set; }

    public string Country { get; set; }

    public string StateProvince { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Address { get; set; }

    public string Website { get; set; }

    public string Email { get; set; }

    public string LogoUrl { get; set; }

    public virtual ICollection<BusinessBanking> BusinessBankings { get; set; } = new List<BusinessBanking>();

    public virtual ICollection<BusinessCategory> BusinessCategories { get; set; } = new List<BusinessCategory>();

    public virtual ICollection<BusinessCurrencyConversion> BusinessCurrencyConversions { get; set; } = new List<BusinessCurrencyConversion>();

    public virtual ICollection<BusinessFinancialInfo> BusinessFinancialInfos { get; set; } = new List<BusinessFinancialInfo>();

    public virtual ICollection<BusinessFiscalYear> BusinessFiscalYears { get; set; } = new List<BusinessFiscalYear>();

    public virtual ICollection<BusinessProduct> BusinessProducts { get; set; } = new List<BusinessProduct>();

    public virtual ICollection<BusinessProject> BusinessProjects { get; set; } = new List<BusinessProject>();

    public virtual ICollection<BusinessService> BusinessServices { get; set; } = new List<BusinessService>();

    public virtual ICollection<BusinessUser> BusinessUsers { get; set; } = new List<BusinessUser>();

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual Language Language { get; set; }

    public virtual ICollection<Salesman> Salesmen { get; set; } = new List<Salesman>();

    public virtual ICollection<SubAccount> SubAccounts { get; set; } = new List<SubAccount>();

    public virtual BusinessType Type { get; set; }

    public virtual ICollection<Currency> Currencies { get; set; } = new List<Currency>();
}