// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessFiscalYear
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Title { get; set; }

    public int InventoryValuationMethod { get; set; }

    public virtual Business Business { get; set; }

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();
}