// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessCurrencyConversion
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public int CurrencyId { get; set; }

    public decimal MainValue { get; set; }

    public virtual Business Business { get; set; }

    public virtual Currency Currency { get; set; }
}