// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessBankingInfo
{
    public int Id { get; set; }

    public int BusinessBankingId { get; set; }

    public string Branch { get; set; }

    public string AccountNumber { get; set; }

    public string CardNumber { get; set; }

    public string Iban { get; set; }

    public string HoldersName { get; set; }

    public string Posnumber { get; set; }

    public string MobileNumberRegistered { get; set; }

    public string PaymentSwitchNumber { get; set; }

    public string AcceptanceNumber { get; set; }

    public virtual BusinessBanking BusinessBanking { get; set; }
}