// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class BusinessService
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public string ProductCode { get; set; }

    public string Barcode { get; set; }

    public int CategoryId { get; set; }

    public int SalesPrice { get; set; }

    public string SalesInformation { get; set; }

    public int PurchaseCost { get; set; }

    public string PurchaseInformation { get; set; }

    public string MainUnit { get; set; }

    public string Note { get; set; }

    public string SubUnit { get; set; }

    public int UnitConversionFactor { get; set; }

    public bool SalesTaxable { get; set; }

    public int SalesTax { get; set; }

    public bool PurchaseTaxable { get; set; }

    public int PurchaseTax { get; set; }

    public int TaxId { get; set; }

    public int TaxUnitId { get; set; }

    public int IranianTaxTypeId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Business Business { get; set; }

    public virtual BusinessCategory Category { get; set; }

    public virtual ICollection<ServicePriceList> ServicePriceLists { get; set; } = new List<ServicePriceList>();
}