// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class ContactAddressInfo
{
    public int Id { get; set; }

    public int ContactId { get; set; }

    public string Country { get; set; }

    public string StateProvince { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Address { get; set; }

    public virtual Contact Contact { get; set; }
}