// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class ContactGeneralInfo
{
    public int Id { get; set; }

    public int ContactId { get; set; }

    public int FinancialCredit { get; set; }

    public int IranianTaxType { get; set; }

    public string NationalCode { get; set; }

    public string EconomicCode { get; set; }

    public string RegistrationNumber { get; set; }

    public string BranchCode { get; set; }

    public string Note { get; set; }

    public virtual Contact Contact { get; set; }
}