// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class ContactPhoneInfo
{
    public int Id { get; set; }

    public int ContactId { get; set; }

    public string Phone { get; set; }

    public string Phone1 { get; set; }

    public string Mobile { get; set; }

    public string Mobile2 { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public virtual Contact Contact { get; set; }
}