// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class Contact
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public bool IsActive { get; set; }

    public string Company { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string DisplayName { get; set; }

    public int CategoryId { get; set; }

    public string ImageUrl { get; set; }

    public bool IsCustomer { get; set; }

    public bool IsVendor { get; set; }

    public bool IsStockholder { get; set; }

    public bool Employee { get; set; }

    public virtual Business Business { get; set; }

    public virtual BusinessCategory Category { get; set; }

    public virtual ICollection<ContactAddressInfo> ContactAddressInfos { get; set; } = new List<ContactAddressInfo>();

    public virtual ICollection<ContactBankAccountInfo> ContactBankAccountInfos { get; set; } = new List<ContactBankAccountInfo>();

    public virtual ICollection<ContactGeneralInfo> ContactGeneralInfos { get; set; } = new List<ContactGeneralInfo>();

    public virtual ICollection<ContactPhoneInfo> ContactPhoneInfos { get; set; } = new List<ContactPhoneInfo>();

    public virtual ICollection<Stockholder> Stockholders { get; set; } = new List<Stockholder>();
    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();
}