// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Businesses_Accounting.Models;

public partial class Currency
{
    public Currency() { }
    public Currency(Currency currency, bool fixValeus)
    {
        Id = currency.Id;
        Name = currency.Name;
        ShortName = currency.ShortName;
        DisplayName = currency.DisplayName;
        AccountingJournals  = currency.AccountingJournals;
        BusinessBankings = currency.BusinessBankings;   
        BusinessCurrencyConversions = currency.BusinessCurrencyConversions; 
        ProductPriceLists = currency.ProductPriceLists;
        ServicePriceLists = currency.ServicePriceLists;
        FixValeus = fixValeus;
    }
    [NotMapped]
    public  bool FixValeus { get; private set; }
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string DisplayName { get; set; }

    public virtual ICollection<AccountingJournal> AccountingJournals { get; set; } = new List<AccountingJournal>();

    public virtual ICollection<BusinessBanking> BusinessBankings { get; set; } = new List<BusinessBanking>();

    public virtual ICollection<BusinessCurrencyConversion> BusinessCurrencyConversions { get; set; } = new List<BusinessCurrencyConversion>();

    public virtual ICollection<ProductPriceList> ProductPriceLists { get; set; } = new List<ProductPriceList>();

    public virtual ICollection<ServicePriceList> ServicePriceLists { get; set; } = new List<ServicePriceList>();
}