// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class Currency
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string DisplayName { get; set; }

    public virtual ICollection<AccountingJournal> AccountingJournals { get; set; } = new List<AccountingJournal>();

    public virtual ICollection<BusinessBanking> BusinessBankings { get; set; } = new List<BusinessBanking>();

    public virtual ICollection<BusinessCurrencyConversion> BusinessCurrencyConversions { get; set; } = new List<BusinessCurrencyConversion>();

    public virtual ICollection<ProductPriceList> ProductPriceLists { get; set; } = new List<ProductPriceList>();

    public virtual ICollection<ServicePriceList> ServicePriceLists { get; set; } = new List<ServicePriceList>();

    public virtual ICollection<Business> Businesses { get; set; } = new List<Business>();
}