// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Businesses_Accounting.Models;

public partial class Document
{
    public int Id { get; set; }

    public int BusinessFiscalYearId { get; set; }

    public int Number { get; set; }

    public int Reference { get; set; }

    public DateTime InsertDate { get; set; }

    public int? ProjectId { get; set; }
    [Display(Name = "توضیحات")]
    public string Description { get; set; }
    [Display(Name = "تاریخ سند")]
    public DateTime DocumentDate { get; set; }

    public int Amount { get; set; }
    public int? ContactId { get; set; }

    public virtual ICollection<AccountingJournal> AccountingJournals { get; set; } = new List<AccountingJournal>();

    public virtual BusinessFiscalYear BusinessFiscalYear { get; set; }

    public virtual BusinessProject Project { get; set; }
    public virtual Contact Contact { get; set; }
}