// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class Language
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Flag { get; set; }

    public virtual ICollection<Business> Businesses { get; set; } = new List<Business>();
}