// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class ProductPriceList
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Title { get; set; }

    public int Price { get; set; }

    public int CurrencyId { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual BusinessProduct Product { get; set; }
}