// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class Salesman
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public bool IsActive { get; set; }

    public string Name { get; set; }

    public int SalesPercent { get; set; }

    public int SalesReturnPercent { get; set; }

    public bool ExcludeItemDiscount { get; set; }

    public bool ExcludeAdditionsAndDeductionsOfInvoice { get; set; }

    public bool AddJournalExpenseRecordInInvoiceDocument { get; set; }

    public string Note { get; set; }

    public virtual Business Business { get; set; }

    public virtual ICollection<SalesmenPercentCategory> SalesmenPercentCategories { get; set; } = new List<SalesmenPercentCategory>();

    public virtual ICollection<SalesmenPercentProduct> SalesmenPercentProducts { get; set; } = new List<SalesmenPercentProduct>();
}