// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class SalesmenPercentProduct
{
    public int Id { get; set; }

    public int SalesmenId { get; set; }

    public int SalesPercent { get; set; }

    public int SalesReturnPercent { get; set; }

    public int ObjectId { get; set; }

    public int ObjectType { get; set; }

    public virtual Salesman Salesmen { get; set; }
}