// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class SalesmenPercentCategory
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public int SalesmenId { get; set; }

    public int SalesPercent { get; set; }

    public int SalesReturnPercent { get; set; }

    public virtual BusinessCategory Category { get; set; }

    public virtual Salesman Salesmen { get; set; }
}