// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Businesses_Accounting.Models;

public partial class SubAccount
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int ObjetcId { get; set; }

    public int ObjetcType { get; set; }

    public int? BusinessId { get; set; }

    public virtual ICollection<AccountingJournal> AccountingJournals { get; set; } = new List<AccountingJournal>();

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual Business Business { get; set; }
}