USE [BusinessesAccounting_db]
GO
IF NOT EXISTS ( SELECT * FROM [dbo].[Language] WHERE [Id]<3)
BEGIN
INSERT [dbo].[Language] ([Id], [Name], [Flag]) VALUES (1, N'فارسی', N'')
INSERT [dbo].[Language] ([Id], [Name], [Flag]) VALUES (2, N'English', N'')
END
GO

IF NOT EXISTS ( SELECT * FROM [dbo].[Currencies] WHERE [Id]<304)
BEGIN
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (1, N'ADP - پزتای آندورا', N'ADP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (2, N'AED - درهم امارات متحدهٔ عربی', N'AED', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (3, N'AFA - افغانی افغانستان (۱۹۲۷ تا ۲۰۰۲)', N'AFA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (4, N'AFN - افغانی افغانستان', N'AFN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (5, N'ALK - ALK', N'ALK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (6, N'ALL - لک آلبانی', N'ALL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (7, N'AMD - درام ارمنستان', N'AMD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (8, N'ANG - گیلدر آنتیل هلند', N'ANG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (9, N'AOA - کوانزای آنگولا', N'AOA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (10, N'AOK - AOK', N'AOK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (11, N'AON - AON', N'AON', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (12, N'AOR - AOR', N'AOR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (13, N'ARA - ARA', N'ARA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (14, N'ARL - ARL', N'ARL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (15, N'ARM - ARM', N'ARM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (16, N'ARP - پزوی آرژانتین (۱۹۸۳ تا ۱۹۸۵)‏', N'ARP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (17, N'ARS - پزوی آرژانتین', N'ARS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (18, N'ATS - شیلینگ اتریش', N'ATS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (19, N'AUD - دلار استرالیا', N'AUD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (20, N'AWG - فلورین آروبا', N'AWG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (21, N'AZM - منات جمهوری آذربایجان (۱۹۹۳ تا ۲۰۰۶)', N'AZM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (22, N'AZN - منات جمهوری آذربایجان', N'AZN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (23, N'BAD - دینار بوسنی و هرزگوین (۱۹۹۲ تا ۱۹۹۴)', N'BAD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (24, N'BAM - مارک تبدیل‌پذیر بوسنی و هرزگوین', N'BAM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (25, N'BAN - BAN', N'BAN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (26, N'BBD - دلار باربادوس', N'BBD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (27, N'BDT - تاکای بنگلادش', N'BDT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (28, N'BEC - BEC', N'BEC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (29, N'BEF - فرانک بلژیک', N'BEF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (30, N'BEL - فرانک بلژیک (مالی)', N'BEL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (31, N'BGL - BGL', N'BGL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (32, N'BGM - BGM', N'BGM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (33, N'BGN - لف بلغارستان', N'BGN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (34, N'BGO - BGO', N'BGO', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (35, N'BHD - دینار بحرین', N'BHD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (36, N'BIF - فرانک بوروندی', N'BIF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (37, N'BMD - دلار برمودا', N'BMD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (38, N'BND - دلار برونئی', N'BND', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (39, N'BOB - بولیویانوی بولیوی', N'BOB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (40, N'BOL - BOL', N'BOL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (41, N'BOP - پزوی بولیوی', N'BOP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (42, N'BOV - BOV', N'BOV', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (43, N'BRB - BRB', N'BRB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (44, N'BRC - BRC', N'BRC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (45, N'BRE - BRE', N'BRE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (46, N'BRL - رئال برزیل', N'BRL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (47, N'BRN - BRN', N'BRN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (48, N'BRR - BRR', N'BRR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (49, N'BRZ - BRZ', N'BRZ', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (50, N'BSD - دلار باهاما', N'BSD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (51, N'BTN - انگولتروم بوتان', N'BTN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (52, N'BUK - BUK', N'BUK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (53, N'BWP - پولای بوتسوانا', N'BWP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (54, N'BYB - روبل جدید بیلوروسی (۱۹۹۴ تا ۱۹۹۹)', N'BYB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (55, N'BYN - روبل بلاروسی', N'BYN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (56, N'BYR - روبل بلاروسی (۲۰۱۶–۲۰۰۰)', N'BYR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (57, N'BZD - دلار بلیز', N'BZD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (58, N'CAD - دلار کانادا', N'CAD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (59, N'CDF - فرانک کنگو', N'CDF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (60, N'CHE - CHE', N'CHE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (61, N'CHF - فرانک سوئیس', N'CHF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (62, N'CHW - CHW', N'CHW', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (63, N'CLE - CLE', N'CLE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (64, N'CLF - CLF', N'CLF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (65, N'CLP - پزوی شیلی', N'CLP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (66, N'CNH - یوآن چین (برون‌مرزی)', N'CNH', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (67, N'CNX - CNX', N'CNX', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (68, N'CNY - یوآن چین', N'CNY', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (69, N'COP - پزوی کلمبیا', N'COP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (70, N'COU - COU', N'COU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (71, N'CRC - کولون کاستاریکا', N'CRC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (72, N'CSD - دینار صربستان (۲۰۰۲ تا ۲۰۰۶)', N'CSD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (73, N'CSK - CSK', N'CSK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (74, N'CUC - پزوی تبدیل‌پذیر کوبا', N'CUC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (75, N'CUP - پزوی کوبا', N'CUP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (76, N'CVE - اسکودوی کیپ‌ورد', N'CVE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (77, N'CYP - پوند قبرس', N'CYP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (78, N'CZK - کورونای جمهوری چک', N'CZK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (79, N'DDM - مارک آلمان شرقی', N'DDM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (80, N'DEM - مارک آلمان', N'DEM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (81, N'DJF - فرانک جیبوتی', N'DJF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (82, N'DKK - کرون دانمارک', N'DKK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (83, N'DOP - پزوی جمهوری دومینیکن', N'DOP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (84, N'DZD - دینار الجزایر', N'DZD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (85, N'ECS - ECS', N'ECS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (86, N'ECV - ECV', N'ECV', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (87, N'EEK - EEK', N'EEK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (88, N'EGP - پوند مصر', N'EGP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (89, N'ERN - ناکفای اریتره', N'ERN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (90, N'ESA - ESA', N'ESA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (91, N'ESB - ESB', N'ESB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (92, N'ESP - ESP', N'ESP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (93, N'ETB - بیر اتیوپی', N'ETB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (94, N'EUR - یورو', N'EUR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (95, N'FIM - FIM', N'FIM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (96, N'FJD - دلار فیجی', N'FJD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (97, N'FKP - پوند جزایر فالکلند', N'FKP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (98, N'FRF - فرانک فرانسه', N'FRF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (99, N'GBP - پوند بریتانیا', N'GBP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (100, N'GEK - GEK', N'GEK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (101, N'GEL - لاری گرجستان', N'GEL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (102, N'GHC - GHC', N'GHC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (103, N'GHS - سدی غنا', N'GHS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (104, N'GIP - پوند جبل‌الطارق', N'GIP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (105, N'GMD - دالاسی گامبیا', N'GMD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (106, N'GNF - فرانک گینه', N'GNF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (107, N'GNS - GNS', N'GNS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (108, N'GQE - GQE', N'GQE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (109, N'GRD - دراخمای یونان', N'GRD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (110, N'GTQ - کتزال گواتمالا', N'GTQ', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (111, N'GWE - GWE', N'GWE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (112, N'GWP - پزوی گینهٔ بیسائو', N'GWP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (113, N'GYD - دلار گویانا', N'GYD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (114, N'HKD - دلار هنگ‌کنگ', N'HKD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (115, N'HNL - لمپیرای هندوراس', N'HNL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (116, N'HRD - دینار کرواسی', N'HRD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (117, N'HRK - کونای کرواسی', N'HRK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (118, N'HTG - گورد هائیتی', N'HTG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (119, N'HUF - فورینت مجارستان', N'HUF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (120, N'IDR - روپیهٔ اندونزی', N'IDR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (121, N'IEP - پوند ایرلند', N'IEP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (122, N'ILP - ILP', N'ILP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (123, N'ILR - ILR', N'ILR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (124, N'INR - روپیهٔ هند', N'INR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (125, N'IQD - دینار عراق', N'IQD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (126, N'IRR - ریال ایران', N'IRR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (127, N'IRT - تومان ایران', N'IRT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (128, N'ISJ - ISJ', N'ISJ', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (129, N'ISK - کرونای ایسلند', N'ISK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (130, N'ITL - لیرهٔ ایتالیا', N'ITL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (131, N'JMD - دلار جامائیکا', N'JMD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (132, N'JOD - دینار اردن', N'JOD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (133, N'JPY - ین ژاپن', N'JPY', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (134, N'KES - شیلینگ کنیا', N'KES', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (135, N'KGS - سوم قرقیزستان', N'KGS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (136, N'KHR - ری‌یل کامبوج', N'KHR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (137, N'KMF - فرانک کومورو', N'KMF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (138, N'KPW - وون کرهٔ شمالی', N'KPW', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (139, N'KRH - KRH', N'KRH', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (140, N'KRO - KRO', N'KRO', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (141, N'KRW - وون کرهٔ جنوبی', N'KRW', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (142, N'KWD - دینار کویت', N'KWD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (143, N'KYD - دلار جزایر کِیمن', N'KYD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (144, N'KZT - تنگهٔ قزاقستان', N'KZT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (145, N'LAK - کیپ لائوس', N'LAK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (146, N'LBP - لیرهٔ لبنان', N'LBP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (147, N'LKR - روپیهٔ سری‌لانکا', N'LKR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (148, N'LRD - دلار لیبریا', N'LRD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (149, N'LSL - لوتی لسوتو', N'LSL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (150, N'LTL - لیتاس لیتوانی', N'LTL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (151, N'LTT - LTT', N'LTT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (152, N'LUC - LUC', N'LUC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (153, N'LUF - فرانک لوکزامبورگ', N'LUF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (154, N'LUL - فرانک مالی لوگزامبورگ', N'LUL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (155, N'LVL - لاتس لتونی', N'LVL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (156, N'LVR - روبل لتونی', N'LVR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (157, N'LYD - دینار لیبی', N'LYD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (158, N'MAD - درهم مراکش', N'MAD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (159, N'MAF - فرانک مراکش', N'MAF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (160, N'MCF - MCF', N'MCF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (161, N'MDC - MDC', N'MDC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (162, N'MDL - لئوی مولداوی', N'MDL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (163, N'MGA - آریاری مالاگاسی', N'MGA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (164, N'MGF - فرانک ماداگاسکار', N'MGF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (165, N'MKD - دینار مقدونیه', N'MKD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (166, N'MKN - MKN', N'MKN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (167, N'MLF - فرانک مالی', N'MLF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (168, N'MMK - کیات میانمار', N'MMK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (169, N'MNT - توگریک مغولستان', N'MNT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (170, N'MOP - پاتاکای ماکائو', N'MOP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (171, N'MRO - اوگوئیای موریتانی (۱۹۷۳ تا ۲۰۱۷)', N'MRO', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (172, N'MRU - اوگوئیای موریتانی', N'MRU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (173, N'MTL - لیرهٔ مالت', N'MTL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (174, N'MTP - پوند مالت', N'MTP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (175, N'MUR - روپیهٔ موریس', N'MUR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (176, N'MVP - MVP', N'MVP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (177, N'MVR - روپیهٔ مالدیو', N'MVR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (178, N'MWK - کواچای مالاوی', N'MWK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (179, N'MXN - پزوی مکزیک', N'MXN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (180, N'MXP - پزوی نقرهٔ مکزیک (۱۸۶۱ تا ۱۹۹۲)', N'MXP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (181, N'MXV - MXV', N'MXV', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (182, N'MYR - رینگیت مالزی', N'MYR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (183, N'MZE - اسکودوی موزامبیک', N'MZE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (184, N'MZM - MZM', N'MZM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (185, N'MZN - متیکال موزامبیک', N'MZN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (186, N'NAD - دلار نامیبیا', N'NAD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (187, N'NGN - نایرای نیجریه', N'NGN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (188, N'NIC - NIC', N'NIC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (189, N'NIO - کوردوبای نیکاراگوئه', N'NIO', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (190, N'NLG - گیلدر هلند', N'NLG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (191, N'NOK - کرون نروژ', N'NOK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (192, N'NPR - روپیهٔ نپال', N'NPR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (193, N'NZD - دلار زلاند نو', N'NZD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (194, N'OMR - ریال عمان', N'OMR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (195, N'PAB - بالبوای پاناما', N'PAB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (196, N'PEI - PEI', N'PEI', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (197, N'PEN - نوئووسول پرو', N'PEN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (198, N'PES - PES', N'PES', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (199, N'PGK - کینای پاپوا گینهٔ نو', N'PGK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (200, N'PHP - پزوی فیلیپین', N'PHP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (201, N'PKR - روپیهٔ پاکستان', N'PKR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (202, N'PLN - زواتی لهستان', N'PLN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (203, N'PLZ - PLZ', N'PLZ', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (204, N'PTE - اسکودوی پرتغال', N'PTE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (205, N'PYG - گوارانی پاراگوئه', N'PYG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (206, N'QAR - ریال قطر', N'QAR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (207, N'RHD - دلار رودزیا', N'RHD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (208, N'ROL - ROL', N'ROL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (209, N'RON - لئوی رومانی', N'RON', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (210, N'RSD - دینار صربستان', N'RSD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (211, N'RUB - روبل روسیه', N'RUB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (212, N'RUR - روبل روسیه (۱۹۹۱ تا ۱۹۹۸)', N'RUR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (213, N'RWF - فرانک رواندا', N'RWF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (214, N'SAR - ریال سعودی', N'SAR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (215, N'SBD - دلار جزایر سلیمان', N'SBD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (216, N'SCR - روپیهٔ سیشل', N'SCR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (217, N'SDD - دینار سودان (۱۹۹۲ تا ۲۰۰۷)', N'SDD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (218, N'SDG - پوند سودان', N'SDG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (219, N'SDP - SDP', N'SDP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (220, N'SEK - کرون سوئد', N'SEK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (221, N'SGD - دلار سنگاپور', N'SGD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (222, N'SHP - پوند سنت هلن', N'SHP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (223, N'SIT - SIT', N'SIT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (224, N'SKK - SKK', N'SKK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (225, N'SLL - لئون سیرالئون', N'SLL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (226, N'SOS - شیلینگ سومالی', N'SOS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (227, N'SRD - دلار سورینام', N'SRD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (228, N'SRG - گیلدر سورینام', N'SRG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (229, N'SSP - پوند سودان جنوبی', N'SSP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (230, N'STD - دوبرای سائوتومه و پرنسیپ (۱۹۷۷ تا ۲۰۱۷)', N'STD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (231, N'STN - دوبرای سائوتومه و پرنسیپ', N'STN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (232, N'SUR - روبل شوروی', N'SUR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (233, N'SVC - SVC', N'SVC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (234, N'SYP - لیرهٔ سوریه', N'SYP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (235, N'SZL - لیلانگنی سوازیلند', N'SZL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (236, N'THB - بات تایلند', N'THB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (237, N'TJR - روبل تاجیکستان', N'TJR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (238, N'TJS - سامانی تاجیکستان', N'TJS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (239, N'TMM - منات ترکمنستان (۱۹۹۳ تا ۲۰۰۹)', N'TMM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (240, N'TMT - منات ترکمنستان', N'TMT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (241, N'TND - دینار تونس', N'TND', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (242, N'TOP - پاآنگای تونگا', N'TOP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (243, N'TPE - اسکودوی تیمور', N'TPE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (244, N'TRL - لیرهٔ ترکیه (۱۹۲۲ تا ۲۰۰۵)', N'TRL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (245, N'TRY - لیرهٔ ترکیه', N'TRY', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (246, N'TTD - دلار ترینیداد و توباگو', N'TTD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (247, N'TWD - دلار جدید تایوان', N'TWD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (248, N'TZS - شیلینگ تانزانیا', N'TZS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (249, N'UAH - هریونیای اوکراین', N'UAH', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (250, N'UAK - UAK', N'UAK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (251, N'UGS - شیلینگ اوگاندا (۱۹۶۶ تا ۱۹۸۷)', N'UGS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (252, N'UGX - شیلینگ اوگاندا', N'UGX', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (253, N'USD - دلار امریکا', N'USD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (254, N'USN - دلار امریکا (روز بعد)', N'USN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (255, N'USS - دلار امریکا (همان روز)', N'USS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (256, N'UYI - UYI', N'UYI', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (257, N'UYP - پزوی اوروگوئه (۱۹۷۵ تا ۱۹۹۳)', N'UYP', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (258, N'UYU - پزوی اوروگوئه', N'UYU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (259, N'UYW - UYW', N'UYW', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (260, N'UZS - سوم ازبکستان', N'UZS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (261, N'VEB - بولیوار ونزوئلا (۱۸۷۱ تا ۲۰۰۸)', N'VEB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (262, N'VEF - بولیوار ونزوئلا (۲۰۰۸ تا ۲۰۱۸)', N'VEF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (263, N'VES - بولیوار ونزوئلا', N'VES', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (264, N'VND - دانگ ویتنام', N'VND', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (265, N'VNN - VNN', N'VNN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (266, N'VUV - واتوی وانوواتو', N'VUV', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (267, N'WST - تالای ساموا', N'WST', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (268, N'XAF - فرانک CFA مرکز افریقا', N'XAF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (269, N'XAG - نقره', N'XAG', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (270, N'XAU - طلا', N'XAU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (271, N'XBA - XBA', N'XBA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (272, N'XBB - XBB', N'XBB', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (273, N'XBC - XBC', N'XBC', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (274, N'XBD - XBD', N'XBD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (275, N'XCD - دلار شرق کارائیب', N'XCD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (276, N'XDR - XDR', N'XDR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (277, N'XEU - XEU', N'XEU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (278, N'XFO - فرانک طلای فرانسه', N'XFO', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (279, N'XFU - XFU', N'XFU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (280, N'XOF - فرانک CFA غرب افریقا', N'XOF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (281, N'XPD - پالادیم', N'XPD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (282, N'XPF - فرانک اقیانوسیه', N'XPF', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (283, N'XPT - پلاتین', N'XPT', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (284, N'XRE - XRE', N'XRE', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (285, N'XSU - XSU', N'XSU', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (286, N'XTS - XTS', N'XTS', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (287, N'XUA - XUA', N'XUA', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (288, N'XXX - ارز نامشخص', N'XXX', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (289, N'YDD - دینار یمن', N'YDD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (290, N'YER - ریال یمن', N'YER', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (291, N'YUD - YUD', N'YUD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (292, N'YUM - YUM', N'YUM', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (293, N'YUN - YUN', N'YUN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (294, N'YUR - YUR', N'YUR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (295, N'ZAL - ZAL', N'ZAL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (296, N'ZAR - راند افریقای جنوبی', N'ZAR', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (297, N'ZMK - کواچای زامبیا (۱۹۶۸ تا ۲۰۱۲)', N'ZMK', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (298, N'ZMW - کواچای زامبیا', N'ZMW', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (299, N'ZRN - ZRN', N'ZRN', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (300, N'ZRZ - ZRZ', N'ZRZ', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (301, N'ZWD - دلار زیمبابوه (۱۹۸۰ تا ۲۰۰۸)', N'ZWD', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (302, N'ZWL - دلار زیمبابوه (۲۰۰۹)', N'ZWL', N'')
INSERT [dbo].[Currencies] ([Id], [Name], [ShortName], [DisplayName]) VALUES (303, N'ZWR - دلار زیمبابوه (۲۰۰۸)', N'ZWR', N'')

END
GO

IF NOT EXISTS ( SELECT * FROM [dbo].[BusinessTypes] WHERE [Id]<14)
BEGIN
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (1, N'شرکت', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (2, N'مغازه', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (3, N'فروشگاه', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (4, N'اتحادیه', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (5, N'باشگاه', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (6, N'موسسه', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (7, N'شخصی', 1)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (8, N'Company', 2)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (9, N'Shop', 2)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (10, N'Store', 2)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (11, N'Union', 2)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (12, N'Club', 2)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (13, N'Institute', 2)
INSERT [dbo].[BusinessTypes] ([Id], [Name], [LanguageId]) VALUES (14, N'Personal', 2)


IF NOT EXISTS ( SELECT * FROM [dbo].[SubAccounts] WHERE [Id]<9)
BEGIN
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'دارایی ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'بدهی ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'حقوق صاحبان سهام',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'بهای تمام شده کالای فروخته شده',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'فروش',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'درآمد',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'هزینه ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'سایر حساب ها',0,0,NULL)
END
GO


IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<9)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی ها',NULL,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهی ها',NULL,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق صاحبان سهام',NULL,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید',NULL,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فروش',NULL,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد',NULL,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه ها',NULL,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب ها',NULL,8)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<27)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های جاری', 1,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های غیر جاری', 1,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهیهای جاری', 2,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهیهای غیر جاری', 2,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق صاحبان سهام',3,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید کالا',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از خرید',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تخفیفات نقدی خرید',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فروش کالا',5 ,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از فروش', 5,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تخفیفات نقدی فروش',5 ,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد های عملیاتی', 6,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد های غیر عملیاتی',6 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های پرسنلی',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های عملیاتی',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های استهلاک',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های غیرعملیاتی', 7,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های بازاریابی و توزیع و فروش', 7,7)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<81)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'موجودی نقد و بانک', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه گذاری های کوتاه مدت', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های دریافتنی', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب های دریافتنی', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش پرداخت ها', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'موجودی کالا', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ملزومات', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های ثابت', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سپرده های بلندمدت', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر دارائی ها', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب ها و اسناد پرداختنی',11 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مالیات بر درآمد پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر درآمد پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب های پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش دریافت ها',11 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب ها و اسناد پرداختنی بلندمدت', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وام پرداختنی', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مزایای پایان خدمت کارکنان', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه اولیه', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'افزایش یا کاهش سرمایه', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اندوخته قانونی', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برداشت ها', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سهم سود و زیان', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود یا زیان انباشته (سنواتی)',13 ,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حاصل از فروش خدمات', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از خرید خدمات', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد اضافه کالا', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حمل کالا', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حاصل از سرمایه گذاری',21 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد سود سپرده ها', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر درآمد ها', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد تسعیر ارز', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود فروش اقساطی',21 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه حقوق و دستمزد', 22,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های کارکنان', 22,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید خدمات', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از فروش خدمات', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه حمل کالا',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تعمیر و نگهداری اموال و اثاثیه',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه اجاره محل',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های عمومی', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه ملزومات مصرفی', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه کسری و ضایعات کالا',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه دارایی های ثابت', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک ساختمان',24 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک وسائط نقلیه', 24,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های بانکی', 25,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه تسعیر ارز',25 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه مطالبات سوخت شده',25 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک اثاثیه', 24,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه آگهی و تبلیغات', 26,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه بازاریابی و پورسانت', 26,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های توزیع و فروش',26 ,7)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<136)
BEGIN

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تنخواه گردان', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'صندوق', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بانک',27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وجوه در راه', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه گذاری در بورس', 28,1)

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مطالبات مشکوک الوصول', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد دریافتنی', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد در جریان وصول',29 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود تحقق نیافته فروش اقساطی', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وام کارکنان', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سپرده شرکت در مناقصه و مزایده', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ضمانت نامه بانکی', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر ارزش افزوده خرید',30 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'زمین', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ساختمان',34 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وسائط نقلیه', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اثاثیه اداری', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته ساختمان',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته وسائط نقلیه',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته اثاثیه اداری',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق الامتیازها',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'نرم افزارها',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر دارایی های نامشهود',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های پرداختنی', 38,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد پرداختنی', 38,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات حقوق و دستمزد پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق بیمه پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق و دستمزد پرداختنی',41 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'عیدی و پاداش پرداختنی',41 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر ارزش افزوده فروش',41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش دریافت فروش',42,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر پیش دریافت ها',42 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های پرداختنی بلندمدت', 43,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد پرداختنی بلندمدت',43 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق پایه', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اضافه کار', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق شیفت و شب کاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق نوبت کاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق ماموریت',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فوق العاده مسکن و خواروبار',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق اولاد', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'عیدی و پاداش', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بازخرید سنوات خدمت کارکنان', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بازخرید مرخصی',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه سهم کارفرما', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه بیکاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق مزایای متفرقه', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سفر و ماموریت',62 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ایاب و ذهاب',62 ,7)

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه آب و برق و گاز و تلفن',68 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه پذیرایی و آبدارخانه',68 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود و کارمزد وامها',74 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'کارمزد خدمات بانکی', 74,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'جرائم دیرکرد بانکی',74 ,7)
END
GO