USE [BusinessesAccounting_db]
GO


IF NOT EXISTS ( SELECT * FROM [dbo].[SubAccounts] WHERE [Id]<9)
BEGIN
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'دارایی ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'بدهی ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'حقوق صاحبان سهام',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'بهای تمام شده کالای فروخته شده',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'فروش',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'درآمد',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'هزینه ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'سایر حساب ها',0,0,NULL)
END
GO


IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<9)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی ها',NULL,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهی ها',NULL,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق صاحبان سهام',NULL,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید',NULL,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فروش',NULL,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد',NULL,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه ها',NULL,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب ها',NULL,8)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<27)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های جاری', 1,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های غیر جاری', 1,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهیهای جاری', 2,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهیهای غیر جاری', 2,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق صاحبان سهام',3,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید کالا',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از خرید',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تخفیفات نقدی خرید',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فروش کالا',5 ,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از فروش', 5,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تخفیفات نقدی فروش',5 ,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد های عملیاتی', 6,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد های غیر عملیاتی',6 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های پرسنلی',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های عملیاتی',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های استهلاک',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های غیرعملیاتی', 7,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های بازاریابی و توزیع و فروش', 7,7)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<81)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'موجودی نقد و بانک', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه گذاری های کوتاه مدت', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های دریافتنی', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب های دریافتنی', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش پرداخت ها', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'موجودی کالا', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ملزومات', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های ثابت', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سپرده های بلندمدت', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر دارائی ها', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب ها و اسناد پرداختنی',11 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مالیات بر درآمد پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر درآمد پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب های پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش دریافت ها',11 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب ها و اسناد پرداختنی بلندمدت', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وام پرداختنی', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مزایای پایان خدمت کارکنان', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه اولیه', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'افزایش یا کاهش سرمایه', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اندوخته قانونی', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برداشت ها', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سهم سود و زیان', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود یا زیان انباشته (سنواتی)',13 ,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حاصل از فروش خدمات', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از خرید خدمات', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد اضافه کالا', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حمل کالا', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حاصل از سرمایه گذاری',21 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد سود سپرده ها', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر درآمد ها', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد تسعیر ارز', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود فروش اقساطی',21 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه حقوق و دستمزد', 22,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های کارکنان', 22,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید خدمات', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از فروش خدمات', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه حمل کالا',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تعمیر و نگهداری اموال و اثاثیه',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه اجاره محل',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های عمومی', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه ملزومات مصرفی', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه کسری و ضایعات کالا',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه دارایی های ثابت', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک ساختمان',24 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک وسائط نقلیه', 24,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های بانکی', 25,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه تسعیر ارز',25 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه مطالبات سوخت شده',25 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک اثاثیه', 24,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه آگهی و تبلیغات', 26,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه بازاریابی و پورسانت', 26,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های توزیع و فروش',26 ,7)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<136)
BEGIN

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تنخواه گردان', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'صندوق', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بانک',27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وجوه در راه', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه گذاری در بورس', 28,1)

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مطالبات مشکوک الوصول', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد دریافتنی', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد در جریان وصول',29 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود تحقق نیافته فروش اقساطی', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وام کارکنان', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سپرده شرکت در مناقصه و مزایده', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ضمانت نامه بانکی', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر ارزش افزوده خرید',30 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'زمین', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ساختمان',34 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وسائط نقلیه', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اثاثیه اداری', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته ساختمان',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته وسائط نقلیه',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته اثاثیه اداری',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق الامتیازها',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'نرم افزارها',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر دارایی های نامشهود',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های پرداختنی', 38,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد پرداختنی', 38,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات حقوق و دستمزد پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق بیمه پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق و دستمزد پرداختنی',41 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'عیدی و پاداش پرداختنی',41 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر ارزش افزوده فروش',41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش دریافت فروش',42,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر پیش دریافت ها',42 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های پرداختنی بلندمدت', 43,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد پرداختنی بلندمدت',43 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق پایه', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اضافه کار', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق شیفت و شب کاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق نوبت کاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق ماموریت',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فوق العاده مسکن و خواروبار',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق اولاد', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'عیدی و پاداش', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بازخرید سنوات خدمت کارکنان', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بازخرید مرخصی',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه سهم کارفرما', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه بیکاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق مزایای متفرقه', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سفر و ماموریت',62 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ایاب و ذهاب',62 ,7)

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه آب و برق و گاز و تلفن',68 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه پذیرایی و آبدارخانه',68 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود و کارمزد وامها',74 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'کارمزد خدمات بانکی', 74,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'جرائم دیرکرد بانکی',74 ,7)
END
GO