USE [BusinessesAccounting_db]
GO
IF NOT EXISTS ( SELECT * FROM [dbo].[BankingTypes] WHERE [Id]<4)
BEGIN
INSERT [dbo].[BankingTypes] ([Name]) VALUES ( N'بانک')
INSERT [dbo].[BankingTypes] ([Name]) VALUES ( N'صندوق')
INSERT [dbo].[BankingTypes] ([Name]) VALUES ( N'تنخواه گردان')
END
GO

IF NOT EXISTS ( SELECT * FROM [dbo].[Language] WHERE [Id]<3)
BEGIN
INSERT [dbo].[Language] ( [Name], [Flag]) VALUES ( N'فارسی', N'')
INSERT [dbo].[Language] ( [Name], [Flag]) VALUES ( N'English', N'')
END
GO

IF NOT EXISTS ( SELECT * FROM [dbo].[Currencies] WHERE [Id]<304)
BEGIN
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ADP - پزتای آندورا', N'ADP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AED - درهم امارات متحدهٔ عربی', N'AED', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AFA - افغانی افغانستان (۱۹۲۷ تا ۲۰۰۲)', N'AFA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AFN - افغانی افغانستان', N'AFN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ALK - ALK', N'ALK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ALL - لک آلبانی', N'ALL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AMD - درام ارمنستان', N'AMD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ANG - گیلدر آنتیل هلند', N'ANG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AOA - کوانزای آنگولا', N'AOA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AOK - AOK', N'AOK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AON - AON', N'AON', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AOR - AOR', N'AOR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ARA - ARA', N'ARA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ARL - ARL', N'ARL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ARM - ARM', N'ARM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ARP - پزوی آرژانتین (۱۹۸۳ تا ۱۹۸۵)‏', N'ARP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ARS - پزوی آرژانتین', N'ARS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ATS - شیلینگ اتریش', N'ATS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AUD - دلار استرالیا', N'AUD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AWG - فلورین آروبا', N'AWG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AZM - منات جمهوری آذربایجان (۱۹۹۳ تا ۲۰۰۶)', N'AZM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'AZN - منات جمهوری آذربایجان', N'AZN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BAD - دینار بوسنی و هرزگوین (۱۹۹۲ تا ۱۹۹۴)', N'BAD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BAM - مارک تبدیل‌پذیر بوسنی و هرزگوین', N'BAM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BAN - BAN', N'BAN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BBD - دلار باربادوس', N'BBD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BDT - تاکای بنگلادش', N'BDT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BEC - BEC', N'BEC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BEF - فرانک بلژیک', N'BEF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BEL - فرانک بلژیک (مالی)', N'BEL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BGL - BGL', N'BGL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BGM - BGM', N'BGM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BGN - لف بلغارستان', N'BGN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BGO - BGO', N'BGO', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BHD - دینار بحرین', N'BHD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BIF - فرانک بوروندی', N'BIF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BMD - دلار برمودا', N'BMD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BND - دلار برونئی', N'BND', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BOB - بولیویانوی بولیوی', N'BOB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BOL - BOL', N'BOL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BOP - پزوی بولیوی', N'BOP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BOV - BOV', N'BOV', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRB - BRB', N'BRB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRC - BRC', N'BRC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRE - BRE', N'BRE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRL - رئال برزیل', N'BRL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRN - BRN', N'BRN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRR - BRR', N'BRR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BRZ - BRZ', N'BRZ', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BSD - دلار باهاما', N'BSD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BTN - انگولتروم بوتان', N'BTN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BUK - BUK', N'BUK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BWP - پولای بوتسوانا', N'BWP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BYB - روبل جدید بیلوروسی (۱۹۹۴ تا ۱۹۹۹)', N'BYB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BYN - روبل بلاروسی', N'BYN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BYR - روبل بلاروسی (۲۰۱۶–۲۰۰۰)', N'BYR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'BZD - دلار بلیز', N'BZD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CAD - دلار کانادا', N'CAD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CDF - فرانک کنگو', N'CDF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CHE - CHE', N'CHE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CHF - فرانک سوئیس', N'CHF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CHW - CHW', N'CHW', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CLE - CLE', N'CLE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CLF - CLF', N'CLF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CLP - پزوی شیلی', N'CLP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CNH - یوآن چین (برون‌مرزی)', N'CNH', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CNX - CNX', N'CNX', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CNY - یوآن چین', N'CNY', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'COP - پزوی کلمبیا', N'COP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'COU - COU', N'COU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CRC - کولون کاستاریکا', N'CRC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CSD - دینار صربستان (۲۰۰۲ تا ۲۰۰۶)', N'CSD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CSK - CSK', N'CSK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CUC - پزوی تبدیل‌پذیر کوبا', N'CUC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CUP - پزوی کوبا', N'CUP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CVE - اسکودوی کیپ‌ورد', N'CVE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CYP - پوند قبرس', N'CYP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'CZK - کورونای جمهوری چک', N'CZK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'DDM - مارک آلمان شرقی', N'DDM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'DEM - مارک آلمان', N'DEM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'DJF - فرانک جیبوتی', N'DJF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'DKK - کرون دانمارک', N'DKK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'DOP - پزوی جمهوری دومینیکن', N'DOP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'DZD - دینار الجزایر', N'DZD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ECS - ECS', N'ECS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ECV - ECV', N'ECV', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'EEK - EEK', N'EEK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'EGP - پوند مصر', N'EGP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ERN - ناکفای اریتره', N'ERN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ESA - ESA', N'ESA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ESB - ESB', N'ESB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ESP - ESP', N'ESP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'ETB - بیر اتیوپی', N'ETB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'EUR - یورو', N'EUR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'FIM - FIM', N'FIM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'FJD - دلار فیجی', N'FJD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'FKP - پوند جزایر فالکلند', N'FKP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'FRF - فرانک فرانسه', N'FRF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES (N'GBP - پوند بریتانیا', N'GBP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GEK - GEK', N'GEK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GEL - لاری گرجستان', N'GEL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GHC - GHC', N'GHC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GHS - سدی غنا', N'GHS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GIP - پوند جبل‌الطارق', N'GIP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GMD - دالاسی گامبیا', N'GMD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GNF - فرانک گینه', N'GNF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GNS - GNS', N'GNS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GQE - GQE', N'GQE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GRD - دراخمای یونان', N'GRD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GTQ - کتزال گواتمالا', N'GTQ', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GWE - GWE', N'GWE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GWP - پزوی گینهٔ بیسائو', N'GWP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'GYD - دلار گویانا', N'GYD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'HKD - دلار هنگ‌کنگ', N'HKD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'HNL - لمپیرای هندوراس', N'HNL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'HRD - دینار کرواسی', N'HRD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'HRK - کونای کرواسی', N'HRK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'HTG - گورد هائیتی', N'HTG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'HUF - فورینت مجارستان', N'HUF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'IDR - روپیهٔ اندونزی', N'IDR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'IEP - پوند ایرلند', N'IEP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ILP - ILP', N'ILP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ILR - ILR', N'ILR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'INR - روپیهٔ هند', N'INR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'IQD - دینار عراق', N'IQD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'IRR - ریال ایران', N'IRR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'IRT - تومان ایران', N'IRT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ISJ - ISJ', N'ISJ', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ISK - کرونای ایسلند', N'ISK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ITL - لیرهٔ ایتالیا', N'ITL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'JMD - دلار جامائیکا', N'JMD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'JOD - دینار اردن', N'JOD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'JPY - ین ژاپن', N'JPY', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KES - شیلینگ کنیا', N'KES', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KGS - سوم قرقیزستان', N'KGS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KHR - ری‌یل کامبوج', N'KHR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KMF - فرانک کومورو', N'KMF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KPW - وون کرهٔ شمالی', N'KPW', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KRH - KRH', N'KRH', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KRO - KRO', N'KRO', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KRW - وون کرهٔ جنوبی', N'KRW', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KWD - دینار کویت', N'KWD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KYD - دلار جزایر کِیمن', N'KYD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'KZT - تنگهٔ قزاقستان', N'KZT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LAK - کیپ لائوس', N'LAK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LBP - لیرهٔ لبنان', N'LBP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LKR - روپیهٔ سری‌لانکا', N'LKR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LRD - دلار لیبریا', N'LRD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LSL - لوتی لسوتو', N'LSL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LTL - لیتاس لیتوانی', N'LTL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LTT - LTT', N'LTT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LUC - LUC', N'LUC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LUF - فرانک لوکزامبورگ', N'LUF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LUL - فرانک مالی لوگزامبورگ', N'LUL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LVL - لاتس لتونی', N'LVL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LVR - روبل لتونی', N'LVR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'LYD - دینار لیبی', N'LYD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MAD - درهم مراکش', N'MAD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MAF - فرانک مراکش', N'MAF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MCF - MCF', N'MCF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MDC - MDC', N'MDC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MDL - لئوی مولداوی', N'MDL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MGA - آریاری مالاگاسی', N'MGA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MGF - فرانک ماداگاسکار', N'MGF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MKD - دینار مقدونیه', N'MKD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MKN - MKN', N'MKN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MLF - فرانک مالی', N'MLF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MMK - کیات میانمار', N'MMK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MNT - توگریک مغولستان', N'MNT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MOP - پاتاکای ماکائو', N'MOP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MRO - اوگوئیای موریتانی (۱۹۷۳ تا ۲۰۱۷)', N'MRO', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MRU - اوگوئیای موریتانی', N'MRU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MTL - لیرهٔ مالت', N'MTL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MTP - پوند مالت', N'MTP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MUR - روپیهٔ موریس', N'MUR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MVP - MVP', N'MVP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MVR - روپیهٔ مالدیو', N'MVR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MWK - کواچای مالاوی', N'MWK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MXN - پزوی مکزیک', N'MXN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MXP - پزوی نقرهٔ مکزیک (۱۸۶۱ تا ۱۹۹۲)', N'MXP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MXV - MXV', N'MXV', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MYR - رینگیت مالزی', N'MYR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MZE - اسکودوی موزامبیک', N'MZE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MZM - MZM', N'MZM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'MZN - متیکال موزامبیک', N'MZN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NAD - دلار نامیبیا', N'NAD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NGN - نایرای نیجریه', N'NGN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NIC - NIC', N'NIC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NIO - کوردوبای نیکاراگوئه', N'NIO', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NLG - گیلدر هلند', N'NLG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NOK - کرون نروژ', N'NOK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NPR - روپیهٔ نپال', N'NPR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'NZD - دلار زلاند نو', N'NZD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'OMR - ریال عمان', N'OMR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PAB - بالبوای پاناما', N'PAB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PEI - PEI', N'PEI', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PEN - نوئووسول پرو', N'PEN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PES - PES', N'PES', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PGK - کینای پاپوا گینهٔ نو', N'PGK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PHP - پزوی فیلیپین', N'PHP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PKR - روپیهٔ پاکستان', N'PKR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PLN - زواتی لهستان', N'PLN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PLZ - PLZ', N'PLZ', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PTE - اسکودوی پرتغال', N'PTE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'PYG - گوارانی پاراگوئه', N'PYG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'QAR - ریال قطر', N'QAR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'RHD - دلار رودزیا', N'RHD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ROL - ROL', N'ROL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'RON - لئوی رومانی', N'RON', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'RSD - دینار صربستان', N'RSD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'RUB - روبل روسیه', N'RUB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'RUR - روبل روسیه (۱۹۹۱ تا ۱۹۹۸)', N'RUR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'RWF - فرانک رواندا', N'RWF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SAR - ریال سعودی', N'SAR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SBD - دلار جزایر سلیمان', N'SBD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SCR - روپیهٔ سیشل', N'SCR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SDD - دینار سودان (۱۹۹۲ تا ۲۰۰۷)', N'SDD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SDG - پوند سودان', N'SDG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SDP - SDP', N'SDP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SEK - کرون سوئد', N'SEK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SGD - دلار سنگاپور', N'SGD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SHP - پوند سنت هلن', N'SHP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SIT - SIT', N'SIT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SKK - SKK', N'SKK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SLL - لئون سیرالئون', N'SLL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SOS - شیلینگ سومالی', N'SOS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SRD - دلار سورینام', N'SRD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SRG - گیلدر سورینام', N'SRG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SSP - پوند سودان جنوبی', N'SSP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'STD - دوبرای سائوتومه و پرنسیپ (۱۹۷۷ تا ۲۰۱۷)', N'STD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'STN - دوبرای سائوتومه و پرنسیپ', N'STN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SUR - روبل شوروی', N'SUR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SVC - SVC', N'SVC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SYP - لیرهٔ سوریه', N'SYP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'SZL - لیلانگنی سوازیلند', N'SZL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'THB - بات تایلند', N'THB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TJR - روبل تاجیکستان', N'TJR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TJS - سامانی تاجیکستان', N'TJS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TMM - منات ترکمنستان (۱۹۹۳ تا ۲۰۰۹)', N'TMM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TMT - منات ترکمنستان', N'TMT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TND - دینار تونس', N'TND', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TOP - پاآنگای تونگا', N'TOP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TPE - اسکودوی تیمور', N'TPE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TRL - لیرهٔ ترکیه (۱۹۲۲ تا ۲۰۰۵)', N'TRL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TRY - لیرهٔ ترکیه', N'TRY', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TTD - دلار ترینیداد و توباگو', N'TTD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TWD - دلار جدید تایوان', N'TWD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'TZS - شیلینگ تانزانیا', N'TZS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UAH - هریونیای اوکراین', N'UAH', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UAK - UAK', N'UAK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UGS - شیلینگ اوگاندا (۱۹۶۶ تا ۱۹۸۷)', N'UGS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UGX - شیلینگ اوگاندا', N'UGX', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'USD - دلار امریکا', N'USD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'USN - دلار امریکا (روز بعد)', N'USN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'USS - دلار امریکا (همان روز)', N'USS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UYI - UYI', N'UYI', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UYP - پزوی اوروگوئه (۱۹۷۵ تا ۱۹۹۳)', N'UYP', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UYU - پزوی اوروگوئه', N'UYU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UYW - UYW', N'UYW', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'UZS - سوم ازبکستان', N'UZS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'VEB - بولیوار ونزوئلا (۱۸۷۱ تا ۲۰۰۸)', N'VEB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'VEF - بولیوار ونزوئلا (۲۰۰۸ تا ۲۰۱۸)', N'VEF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'VES - بولیوار ونزوئلا', N'VES', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'VND - دانگ ویتنام', N'VND', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'VNN - VNN', N'VNN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'VUV - واتوی وانوواتو', N'VUV', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'WST - تالای ساموا', N'WST', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XAF - فرانک CFA مرکز افریقا', N'XAF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XAG - نقره', N'XAG', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XAU - طلا', N'XAU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XBA - XBA', N'XBA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XBB - XBB', N'XBB', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XBC - XBC', N'XBC', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XBD - XBD', N'XBD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XCD - دلار شرق کارائیب', N'XCD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XDR - XDR', N'XDR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XEU - XEU', N'XEU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XFO - فرانک طلای فرانسه', N'XFO', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XFU - XFU', N'XFU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XOF - فرانک CFA غرب افریقا', N'XOF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XPD - پالادیم', N'XPD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XPF - فرانک اقیانوسیه', N'XPF', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XPT - پلاتین', N'XPT', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XRE - XRE', N'XRE', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XSU - XSU', N'XSU', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XTS - XTS', N'XTS', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XUA - XUA', N'XUA', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'XXX - ارز نامشخص', N'XXX', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'YDD - دینار یمن', N'YDD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'YER - ریال یمن', N'YER', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'YUD - YUD', N'YUD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'YUM - YUM', N'YUM', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'YUN - YUN', N'YUN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'YUR - YUR', N'YUR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZAL - ZAL', N'ZAL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZAR - راند افریقای جنوبی', N'ZAR', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZMK - کواچای زامبیا (۱۹۶۸ تا ۲۰۱۲)', N'ZMK', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZMW - کواچای زامبیا', N'ZMW', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZRN - ZRN', N'ZRN', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZRZ - ZRZ', N'ZRZ', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZWD - دلار زیمبابوه (۱۹۸۰ تا ۲۰۰۸)', N'ZWD', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZWL - دلار زیمبابوه (۲۰۰۹)', N'ZWL', N'')
INSERT [dbo].[Currencies] ( [Name], [ShortName], [DisplayName]) VALUES ( N'ZWR - دلار زیمبابوه (۲۰۰۸)', N'ZWR', N'')

END
GO

IF NOT EXISTS ( SELECT * FROM [dbo].[BusinessTypes] WHERE [Id]<14)
BEGIN
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'شرکت', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'مغازه', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'فروشگاه', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'اتحادیه', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'باشگاه', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'موسسه', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'شخصی', 1)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'Company', 2)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES (N'Shop', 2)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES ( N'Store', 2)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES ( N'Union', 2)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES ( N'Club', 2)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES ( N'Institute', 2)
INSERT [dbo].[BusinessTypes] ( [Name], [LanguageId]) VALUES ( N'Personal', 2)
END 
GO

IF NOT EXISTS ( SELECT * FROM [dbo].[SubAccounts] WHERE [Id]<9)
BEGIN
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'دارایی ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'بدهی ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'حقوق صاحبان سهام',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'بهای تمام شده کالای فروخته شده',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'فروش',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'درآمد',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'هزینه ها',0,0,NULL)
INSERT INTO [dbo].[SubAccounts]([Name],[ObjetcId],[ObjetcType],[BusinessId]) VALUES (N'سایر حساب ها',0,0,NULL)
END
GO


IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]<9)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی ها',NULL,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهی ها',NULL,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق صاحبان سهام',NULL,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید',NULL,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فروش',NULL,5)--5
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد',NULL,6)--6
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه ها',NULL,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب ها',NULL,8)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE [Id]>8 AND [Id]<27)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های جاری', 1,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های غیر جاری', 1,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهیهای جاری', 2,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بدهیهای غیر جاری', 2,2)--12
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق صاحبان سهام',3,3)--13
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید کالا',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از خرید',4 ,4)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تخفیفات نقدی خرید',4 ,4)--16
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فروش کالا',5 ,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از فروش', 5,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تخفیفات نقدی فروش',5 ,5)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد های عملیاتی', 6,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد های غیر عملیاتی',6 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های پرسنلی',7 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های عملیاتی',7 ,7)--23
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های استهلاک',7 ,7)--24
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های غیرعملیاتی', 7,7)--25
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های بازاریابی و توزیع و فروش', 7,7)--26
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE  [Id]>26 AND [Id]<81)
BEGIN
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'موجودی نقد و بانک', 9,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه گذاری های کوتاه مدت', 9,1)--28
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های دریافتنی', 9,1)--29
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب های دریافتنی', 9,1)--30
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش پرداخت ها', 9,1)--31
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'موجودی کالا', 9,1)--32
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ملزومات', 9,1)--33
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'دارایی های ثابت', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته', 10,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سپرده های بلندمدت', 10,1)--36
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر دارائی ها', 10,1)--37
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب ها و اسناد پرداختنی',11 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مالیات بر درآمد پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر درآمد پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر حساب های پرداختنی', 11,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش دریافت ها',11 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب ها و اسناد پرداختنی بلندمدت', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وام پرداختنی', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مزایای پایان خدمت کارکنان', 12,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه اولیه', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'افزایش یا کاهش سرمایه', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اندوخته قانونی', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برداشت ها', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سهم سود و زیان', 13,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود یا زیان انباشته (سنواتی)',13 ,3)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حاصل از فروش خدمات', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از خرید خدمات', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد اضافه کالا', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حمل کالا', 20,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد حاصل از سرمایه گذاری',21 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد سود سپرده ها', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر درآمد ها', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'درآمد تسعیر ارز', 21,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود فروش اقساطی',21 ,6)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه حقوق و دستمزد', 22,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های کارکنان', 22,7)--62
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'خرید خدمات', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'برگشت از فروش خدمات', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه حمل کالا',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تعمیر و نگهداری اموال و اثاثیه',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه اجاره محل',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های عمومی', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه ملزومات مصرفی', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه کسری و ضایعات کالا',23 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه دارایی های ثابت', 23,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک ساختمان',24 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک وسائط نقلیه', 24,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه های بانکی', 25,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه تسعیر ارز',25 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه مطالبات سوخت شده',25 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه استهلاک اثاثیه', 24,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه آگهی و تبلیغات', 26,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه بازاریابی و پورسانت', 26,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های توزیع و فروش',26 ,7)
END
GO



IF NOT EXISTS ( SELECT * FROM [dbo].[Accounts] WHERE  [Id]>80 AND [Id]<136)
BEGIN

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'تنخواه گردان', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'صندوق', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بانک',27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وجوه در راه', 27,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سرمایه گذاری در بورس', 28,1)

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ذخیره مطالبات مشکوک الوصول', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد دریافتنی', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد در جریان وصول',29 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود تحقق نیافته فروش اقساطی', 29,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وام کارکنان', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سپرده شرکت در مناقصه و مزایده', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ضمانت نامه بانکی', 30,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر ارزش افزوده خرید',30 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'زمین', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ساختمان',34 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'وسائط نقلیه', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اثاثیه اداری', 34,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته ساختمان',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته وسائط نقلیه',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'استهلاک انباشته اثاثیه اداری',35 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق الامتیازها',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'نرم افزارها',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر دارایی های نامشهود',37 ,1)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های پرداختنی', 38,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد پرداختنی', 38,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات حقوق و دستمزد پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق بیمه پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق و دستمزد پرداختنی',41 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'عیدی و پاداش پرداختنی',41 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر هزینه های پرداختنی', 41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'مالیات بر ارزش افزوده فروش',41,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'پیش دریافت فروش',42,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سایر پیش دریافت ها',42 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حساب های پرداختنی بلندمدت', 43,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اسناد پرداختنی بلندمدت',43 ,2)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق پایه', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'اضافه کار', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق شیفت و شب کاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق نوبت کاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق ماموریت',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'فوق العاده مسکن و خواروبار',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حق اولاد', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'عیدی و پاداش', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بازخرید سنوات خدمت کارکنان', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بازخرید مرخصی',61 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه سهم کارفرما', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'بیمه بیکاری', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'حقوق مزایای متفرقه', 61,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سفر و ماموریت',62 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'ایاب و ذهاب',62 ,7)

INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه آب و برق و گاز و تلفن',68 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'هزینه پذیرایی و آبدارخانه',68 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'سود و کارمزد وامها',74 ,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'کارمزد خدمات بانکی', 74,7)
INSERT INTO [dbo].[Accounts]([Name],[ParentId],[SubAccountId]) VALUES (N'جرائم دیرکرد بانکی',74 ,7)
END
GO

DELETE FROM [BusinessesAccounting_db].[dbo].[Accounts] WHERE Id NOT IN (1,4,7,9,10,14,22,27,34,35,61,81,83,84,94,95,97)