CREATE TABLE [dbo].[BusinessServices] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [BusinessId]           INT            NOT NULL,
    [Name]                 NVARCHAR (256) NOT NULL,
    [IsActive]             BIT            NOT NULL,
    [ProductCode]          NVARCHAR (30)  NULL,
    [Barcode]              VARCHAR (1000) NULL,
    [CategoryId]           INT            NOT NULL,
    [SalesPrice]           INT            NOT NULL,
    [SalesInformation]     NVARCHAR (256) NULL,
    [PurchaseCost]         INT            NOT NULL,
    [PurchaseInformation]  NVARCHAR (256) NULL,
    [MainUnit]             NVARCHAR (30)  NULL,
    [Note]                 NVARCHAR (256) NULL,
    [SubUnit]              NVARCHAR (30)  NULL,
    [UnitConversionFactor] INT            NOT NULL,
    [SalesTaxable]         BIT            NOT NULL,
    [SalesTax]             INT            NOT NULL,
    [PurchaseTaxable]      BIT            NOT NULL,
    [PurchaseTax]          INT            NOT NULL,
    [TaxId]                INT            NOT NULL,
    [TaxUnitId]            INT            NOT NULL,
    [IranianTaxTypeId]     INT            NOT NULL,
    [ImageUrl]             NVARCHAR (500) NULL,
    CONSTRAINT [PK_BusinessServices] PRIMARY KEY CLUSTERED ([Id] ASC) ON [BusinessesData],
    CONSTRAINT [FK_BusinessServices_BusinessCategories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[BusinessCategories] ([Id]),
    CONSTRAINT [FK_BusinessServices_Businesses] FOREIGN KEY ([BusinessId]) REFERENCES [dbo].[Businesses] ([Id])
) ON [BusinessesData];

