CREATE TABLE [dbo].[BusinessProducts] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [BusinessId]           INT            NOT NULL,
    [Name]                 NVARCHAR (256) NOT NULL,
    [IsActive]             BIT            CONSTRAINT [DF_BusinessProducts_IsActive] DEFAULT ((1)) NOT NULL,
    [ProductCode]          NVARCHAR (30)  NULL,
    [Barcode]              VARCHAR (1000) NULL,
    [CategoryId]           INT            NOT NULL,
    [SalesPrice]           INT            NOT NULL,
    [SalesInformation]     NVARCHAR (256) NULL,
    [PurchaseCost]         INT            NOT NULL,
    [PurchaseInformation]  NVARCHAR (256) NULL,
    [MainUnit]             NVARCHAR (30)  NULL,
    [Note]                 NVARCHAR (256) NULL,
    [SubUnit]              NVARCHAR (30)  NULL,
    [UnitConversionFactor] INT            CONSTRAINT [DF_BusinessProducts_UnitConversionFactor] DEFAULT ((1)) NOT NULL,
    [TrackQuantity]        BIT            CONSTRAINT [DF_BusinessProducts_TrackQuantity] DEFAULT ((1)) NOT NULL,
    [ReorderPoint]         INT            NOT NULL,
    [MinimumOrder]         INT            NOT NULL,
    [LeadTimeDays]         INT            NOT NULL,
    [SalesTaxable]         BIT            CONSTRAINT [DF_BusinessProducts_SalesTaxable] DEFAULT ((1)) NOT NULL,
    [SalesTax]             INT            NOT NULL,
    [PurchaseTaxable]      BIT            NOT NULL,
    [PurchaseTax]          INT            NOT NULL,
    [TaxId]                INT            NOT NULL,
    [TaxUnitId]            INT            NOT NULL,
    [IranianTaxTypeId]     INT            NOT NULL,
    [ImageUrl]             NVARCHAR (500) NULL,
    CONSTRAINT [PK_BusinessProducts] PRIMARY KEY CLUSTERED ([Id] ASC) ON [BusinessesData],
    CONSTRAINT [FK_BusinessProducts_BusinessCategories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[BusinessCategories] ([Id]),
    CONSTRAINT [FK_BusinessProducts_Businesses] FOREIGN KEY ([BusinessId]) REFERENCES [dbo].[Businesses] ([Id])
) ON [BusinessesData];

